OfferPageProject/Models/ErrorViewModel.cs
namespace OfferPageProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OfferPageProject/Controllers/BaseController.cs
using Microsoft.AspNetCore.Mvc;

namespace OfferPageProject.Controllers
{
    public class BaseController : Controller
    {
        protected void Toastr(string type, string message)
        {
            TempData[$"Toastr{type}"] = message;
        }
    }
}

OfferPageProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OfferPageProject.Models;
using System.Diagnostics;

namespace OfferPageProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OfferPageProject/Controllers/OfferController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfferPageProject.APIService;
using OfferPageProject.Common.DTOs;
using OfferPageProject.Common.VM;
using System.Security.Claims;
using X.PagedList;

namespace OfferPageProject.Controllers
{
    public class OfferController : BaseController
    {
        private readonly IAPIService _apiService;

        public OfferController(IAPIService apiService)
        {
            _apiService = apiService;
        }
        public async Task<IActionResult> Index(string searchText, int pageNumber = 1, int pageSize = 10, string sortColumn = "", string sortOrder = "")
        {
            if (!string.IsNullOrEmpty(searchText))
            {

                List<OfferVM> offers = await _apiService.GetAsync<List<OfferVM>>("offer", HttpContext.Request.Cookies["access-token"]);
                List<OfferVM> selectedOffers = offers.Where(x => x.PackageType.ToString().ToLower().Contains(searchText.ToLower()) || x.ModeName.ToString().ToLower().Contains(searchText.ToLower()) || x.MovementTypeName.ToString().ToLower().Contains(searchText.ToLower()) || x.IncoTermsName.ToString().ToLower().Contains(searchText.ToLower()) || x.Currency.ToString().ToLower().Contains(searchText.ToLower())).ToList();
                // Apply sorting
                selectedOffers = ApplySorting(selectedOffers.AsQueryable(), sortColumn, sortOrder).ToList();

                return View(selectedOffers.ToPagedList(pageNumber, pageSize));
            }
            else
            {
                List<OfferVM> offers = await _apiService.GetAsync<List<OfferVM>>("offer", HttpContext.Request.Cookies["access-token"]);
                offers = ApplySorting(offers.AsQueryable(), sortColumn, sortOrder).ToList();

                return View(offers.ToPagedList(pageNumber, pageSize));
            }

        }

        private IQueryable<OfferVM> ApplySorting(IQueryable<OfferVM> offerList, string sortColumn, string sortOrder)
        {
            switch (sortColumn)
            {
                case "PackageType":
                    offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.PackageType) : offerList.OrderByDescending(p => p.PackageType);
                    break;
				case "CountryName":
					offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.CountryName) : offerList.OrderByDescending(p => p.CountryName);
					break;
				case "ModeName":
                    offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.ModeName) : offerList.OrderByDescending(p => p.ModeName);
                    break;
                case "MovementTypeName":
                    offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.MovementTypeName) : offerList.OrderByDescending(p => p.MovementTypeName);
                    break;
                case "IncoTermsName":
                    offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.IncoTermsName) : offerList.OrderByDescending(p => p.IncoTermsName);
                    break;
                case "CurrencyCode":
                    offerList = sortOrder == "asc" ? offerList.OrderBy(p => p.Currency) : offerList.OrderByDescending(p => p.Currency);
                    break;

                // Add cases for other columns as needed
                default:
                    // Default sorting by Name in ascending order
                    offerList = offerList.OrderByDescending(p => p.CreatedDate);
                    break;
            }

            return offerList;
        }


        public async Task<IActionResult> Create()
        {
            List<CountryDTO> countries = await _apiService.GetAsync<List<CountryDTO>>("country", HttpContext.Request.Cookies["access-token"]);
            List<CityDTO> cities = await _apiService.GetAsync<List<CityDTO>>("city", HttpContext.Request.Cookies["access-token"]);
            List<ModeDTO> modes = await _apiService.GetAsync<List<ModeDTO>>("mode", HttpContext.Request.Cookies["access-token"]);
            List<IncoTermsDTO> incoTerms = await _apiService.GetAsync<List<IncoTermsDTO>>("incoTerms", HttpContext.Request.Cookies["access-token"]);
            List<MovementTypeDTO> movementTypes = await _apiService.GetAsync<List<MovementTypeDTO>>("movementType", HttpContext.Request.Cookies["access-token"]);
            List<Unit1DTO> unit1s = await _apiService.GetAsync<List<Unit1DTO>>("unit1", HttpContext.Request.Cookies["access-token"]);
            List<Unit2DTO> unit2s = await _apiService.GetAsync<List<Unit2DTO>>("unit2", HttpContext.Request.Cookies["access-token"]);

            CreateOfferDTO model = new CreateOfferDTO();
            model.CountryList = countries.Select(c => new SelectListItem
            {
                Value = c.CountryId.ToString(),
                Text = c.Name
            }).ToList();
            model.CityList = cities.Select(d => new SelectListItem
            {
                Value = d.CityId.ToString(),
                Text = d.Name
            }).ToList();

            model.ModeList = modes.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();
            model.IncoTermsList = incoTerms.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();
            model.MovementTypeList = movementTypes.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Name
            }).ToList();
            model.Unit1List = unit1s.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Quantity.ToString() + d.UnitType
            }).ToList();
            model.Unit2List = unit2s.Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text =d.Quantity.ToString()+d.UnitType
            }).ToList();

            return View(model);
        }



        [HttpPost]
        public async Task<IActionResult> Create(CreateOfferDTO model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                await _apiService.PostAsync<CreateOfferDTO, CreateOfferDTO>("offer", model, HttpContext.Request.Cookies["access-token"]);
                Toastr("success", "Create Success");
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Toastr("error", $"Create Failed : {ex.Message}");
                return View(model);
            }

        }
        [HttpGet]
        public async Task<JsonResult> GetCities(int countryId)
        {
            List<CityDTO> cityList = await _apiService.GetAsyncWoToken<List<CityDTO>>("city");
            var cities = cityList
                .Where(d => d.CountryId == countryId)
                .Select(d => new SelectListItem
                {
                    Value = d.CityId.ToString(),
                    Text = d.Name
                })
                .ToList();

            return Json(cities);
        }


    }
}

OfferPageProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OfferPageProject/Views/Offer/Create.cshtml
@using OfferPageProject.Common.Extensions;
@using OfferPageProject.Domain.Enum;
@model OfferPageProject.Common.DTOs.CreateOfferDTO

@{
    ViewData["Title"] = "Create";
}

<h1 class="p-4">Create Offer</h1>

<hr />
<div class="row p-4">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ModeId" class="control-label">Mode</label>
                <select asp-for="ModeId" asp-items="Model.ModeList" class="form-control">
                    <option value="-1">Select Mode</option>
                </select>
                <span asp-validation-for="ModeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovementTypeId" class="control-label">Movement Type</label>
                <select asp-for="MovementTypeId" asp-items="Model.MovementTypeList" class="form-control">
                    <option value="-1">Select Movement Type</option>
                </select>
                <span asp-validation-for="MovementTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IncotermsId" class="control-label">IncoTerms</label>
                <select asp-for="IncotermsId" asp-items="Model.IncoTermsList" class="form-control">
                    <option value="-1">Select IncoTerms</option>
                </select>
                <span asp-validation-for="IncotermsId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CountryId" class="control-label">Country</label>
                <select asp-for="CountryId" asp-items="Model.CountryList" class="form-control">
                    <option value="">Select Country</option>
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label">City</label>
                <select asp-for="CityId" asp-items="Model.CityList" class="form-control">
                    <option value="">Select City</option>
                </select>
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit1Id" class="control-label">Unit-1</label>
                <select asp-for="Unit1Id" asp-items="Model.Unit1List" class="form-control">
                    <option value="-1">Select Unit-1</option>
                </select>
                <span asp-validation-for="Unit1Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Unit2Id" class="control-label">Unit-2</label>
                <select asp-for="Unit2Id" asp-items="Model.Unit2List" class="form-control">
                    <option value="-1">Select Unit-2</option>
                </select>
                <span asp-validation-for="Unit2Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="PackageType">Package Type:</label>
                <select class="form-control" asp-for="PackageType" asp-items="EnumHelper.GetEnumSelectList<PackageType>()">
                    <option value="-1">Select Package Type</option>
                </select>
            </div>
            <div class="form-group">
                <label for="Currency">Currency:</label>
                <select class="form-control" asp-for="Currency" asp-items="EnumHelper.GetEnumSelectList<Currency>()">
                    <option value="-1">Select Currency</option>
                </select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="p-4">
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @if (TempData.ContainsKey("Toastrsuccess"))
    {
        <script>
            console.log('Toastr success:', '@TempData["Toastrsuccess"]');
            toastr.success('@TempData["Toastrsuccess"]');
        </script>
    }

    @if (TempData.ContainsKey("Toastrerror"))
    {
        <script>
            toastr.error('@TempData["Toastrerror"]');
        </script>
    }
    }



<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    $(document).ready(function () {
        $('#CountryId').change(function () {
            var selectedCountryId = $(this).val();
            $.ajax({
                url: '/Offer/GetCities',
                type: 'GET',
                data: { countryId: selectedCountryId },
                success: function (data) {

                    updateCitiesDropdown(data);
                },
                error: function () {
                    console.error('Error fetching Cities.');
                }
            });
        });

        function updateCitiesDropdown(CityList) {
            var cityDropdown = $('#CityId');
            cityDropdown.empty();
            cityDropdown.append($('<option>').val('').text('Select City'));
            $.each(CityList, function (index, city) {
                cityDropdown.append($('<option>').val(city.value).text(city.text));
            });
        }
    });
</script>

OfferPageProject/Views/Offer/Index.cshtml
@using X.PagedList
@model IPagedList<OfferPageProject.Common.VM.OfferVM>

@{
	ViewData["Title"] = "Index";
}



<body id="page-top">


	<!-- Begin Page Content -->
	<div class="container-fluid">

		<!-- Page Heading -->
		<h1 class="h3 mb-2 text-gray-800">Offer List</h1>

		<!-- DataTales Example -->
		<div class="card shadow mb-4">
			<div class="card-body">
				<div class="table-responsive">
					<div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
						<div class="row">
							<div class="col-sm-12 col-md-9">
								<div class="dataTables_length" id="dataTable_length">
									<p>
										<a asp-action="Create">Create Offer</a>
									</p>
									<label>
										Show
										<select name="dataTable_length" aria-controls="dataTable" class="custom-select custom-select-sm form-control form-control-sm" asp-for="@Model.PageSize" id="pageSizeDropdown">
											<option value="10">10</option>
											<option value="25">25</option>
											<option value="50">50</option>
											<option value="100">100</option>
										</select>
									</label>
								</div>
							</div>
							<div class="col-sm-12 col-md-3">
								<div id="dataTable_filter" class="dataTables_filter">
									<label>
										@using (Html.BeginForm())
										{
											<p>
												@Html.TextBox("searchText")
												<input type="submit" placeholder="Enter value" value="Search" />
											</p>
										}

									</label>
								</div>
							</div>
						</div>

					</div>
					<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
						<thead>
							<tr>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" onclick="sortColumn('Mode')" aria-sort="ascending" style="width: 140px;">
									Mode
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" onclick="sortColumn('MovementTypeName')" aria-sort="ascending" style="width: 140px;">
									Movement Type
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" onclick="sortColumn('IncoTermsName')" aria-sort="ascending" style="width: 140px;">
									IncoTerms
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" onclick="sortColumn('CountryName')" aria-sort="ascending" style="width: 140px;">
									Country
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"  aria-sort="ascending" style="width: 140px;">
									Unit-1
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1" aria-sort="ascending" style="width: 140px;">
									Unit-2
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
									aria-label="Currency.GetDisplayName(Model.Currency)" onclick="sortColumn('CurrencyCode')" aria-sort="ascending"
									style="width: 140px;">
									Currency
								</th>
								<th class="sorting" tabindex="0" aria-controls="dataTable" rowspan="1" colspan="1"
									aria-label="PackageType.GetDisplayName(Model.PackageType)" onclick="sortColumn('PackageType')" aria-sort="ascending"
									style="width: 140px;">
									Package Type
								</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var item in Model)
							{
								<tr>
									<td>@item.ModeName</td>
									<td>@item.MovementTypeName</td>
									<td>@item.IncoTermsName</td>
									<td>@item.CountryName</td>
									<td>@item.Unit1Quantity@item.Unit1Type</td>
									<td>@item.Unit1Quantity@item.Unit2Type</td>
									<td>@item.Currency</td>
									<td>@item.PackageType</td>
								</tr>
							}
						</tbody>

					</table>



					<div class="row">
						<div class="col-md-6 align-self-center">
							<p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Page Number @(Model.PageNumber) / @Model.PageCount , Offer Number @Model.TotalItemCount Qty </p>
						</div>
						<div class="col-md-6">
							<nav class="d-lg-flex justify-content-lg-end dataTables_paginate paging_simple_numbers">
								<ul class="pagination">
									<li class="page-item @(Model.HasPreviousPage ? "" : "disabled")">
										<a class="page-link" aria-label="Previous" href="@(Model.HasPreviousPage ? Url.Action("Index", new { pageNumber = Model.PageNumber - 1 , pageSize=Model.PageSize, searchText=Context.Request.Query["searchText"] }) : "#")">
											<span aria-hidden="true">Previous</span>
										</a>
									</li>
									@for (int i = 1; i <= Model.PageCount; i++)
									{
										<li class="page-item @(i == Model.PageNumber ? "active" : "")">
											<a class="page-link" href="@Url.Action("Index", new { pageNumber = i, pageSize=Model.PageSize,searchText=Context.Request.Query["searchText"] })">@i</a>
										</li>
									}
									<li class="page-item @(Model.HasNextPage ? "" : "disabled")">
										<a class="page-link" aria-label="Next" href="@(Model.HasNextPage ? Url.Action("Index", new { pageNumber = Model.PageNumber + 1, pageSize=Model.PageSize,searchText=Context.Request.Query["searchText"] }) : "#")">
											<span aria-hidden="true">Next</span>
										</a>
									</li>
								</ul>
							</nav>
						</div>
					</div>


				</div>
			</div>
		</div>
	</div>
	</div>
	<!-- /.container-fluid -->
	<!-- End of Main Content -->
	<!-- Footer -->
	<!-- End of Footer -->
	<!-- End of Content Wrapper -->
	<!-- End of Page Wrapper -->
	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>


	@section Scripts {
		@if (TempData.ContainsKey("Toastrsuccess"))
		{
			<script>
				console.log('Toastr success:', '@TempData["Toastrsuccess"]');
				toastr.success('@TempData["Toastrsuccess"]');
			</script>
		}

		@if (TempData.ContainsKey("Toastrerror"))
		{
			<script>
				toastr.error('@TempData["Toastrerror"]');
			</script>
		}
	}


	<!-- Bootstrap core JavaScript-->
	<script src="vendor/jquery/jquery.min.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

	<!-- Custom scripts for all pages-->
	<script src="js/sb-admin-2.min.js"></script>

	<!-- Page level plugins -->
	<script src="vendor/datatables/jquery.dataTables.min.js"></script>
	<script src="vendor/datatables/dataTables.bootstrap4.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="js/demo/datatables-demo.js"></script>

	<script>
		var dropdown = document.getElementById("pageSizeDropdown");

		dropdown.addEventListener("change", function () {
			var selectedPageSize = this.value;
			var searchText = '@Context.Request.Query["searchText"]';

			if (searchText) {
				var url = "/Offer/Index?pageSize=" + selectedPageSize + "&searchText=" + searchText;
			} else {
				var url = "/Offer/Index?pageSize=" + selectedPageSize;
			}

			window.location.href = url;
		});


	</script>

</body>

<script>
	var dropdown1 = document.getElementById("deleteprocess");

	dropdown1.addEventListener("change", function () {
		var selectedPageSize = this.value;


		var url = "/offer/Index?pageSize=" + selectedPageSize;


		window.location.href = url;
	});

	function confirmDelete(id) {
		console.log(id);
		if (confirm("Are you sure you want to delete?")) {
			window.location.href = "/offer/Delete/?id=" + id;
		} else {

		}
	}
</script>

<script>
	function sortColumn(columnName) {
		var currentUrl = window.location.href;

		// Get the current sort order from the URL
		var sortOrder = "asc";
		if (currentUrl.includes("sortOrder=asc")) {
			sortOrder = "desc";
		}

		// Update the URL with the selected column and sort order
		var newUrl = updateQueryStringParameter(currentUrl, "sortColumn", columnName);
		newUrl = updateQueryStringParameter(newUrl, "sortOrder", sortOrder);

		window.location.href = newUrl;
	}

	function updateQueryStringParameter(uri, key, value) {
		var re = new RegExp("([?&])" + key + "=.*?(&|$)", "i");
		var separator = uri.indexOf('?') !== -1 ? "&" : "?";
		if (uri.match(re)) {
			return uri.replace(re, '$1' + key + "=" + value + '$2');
		} else {
			return uri + separator + key + "=" + value;
		}
	}
</script>

OfferPageProject/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>

<html lang="en">

<head>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>OfferPageProject</title>

	<!-- Custom fonts for this template-->
	<link href="/startbootstrap/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
		  rel="stylesheet">

	<!-- Custom styles for this template-->
	<link href="~/startbootstrap/css/sb-admin-2.min.css" rel="stylesheet" />
	<link href="~/startbootstrap/css/sb-admin-2.css" rel="stylesheet" />


</head>

<body id="page-top">

	<!-- Page Wrapper -->
	<div id="wrapper">

		<!-- Sidebar -->
		<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

			<!-- Sidebar - Brand -->
			<a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
				<div class="sidebar-brand-icon rotate-n-15">
					<i class="fas fa-laugh-wink"></i>
				</div>
				<div class="sidebar-brand-text mx-3">Offer Page</div>
			</a>

			<!-- Divider -->
			<hr class="sidebar-divider my-0">

			<!-- Nav Item - Dashboard -->
			<li class="nav-item active">
				<a class="nav-link" asp-controller="Offer" asp-action="Index">
					<i class="fas fa-home"></i>
					<span>Main Page</span>
				</a>
			</li>

			<!-- Divider -->
			<hr class="sidebar-divider">

			<!-- Heading -->
			<div class="sidebar-heading">
				Offer Page
			</div>


				<!-- Nav Item - Personel Ekleme Collapse Menu -->
				<li class="nav-item">
					<a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePersonnel"
					   aria-expanded="true" aria-controls="collapsePersonnel">
						<i class="fas fa-thin fa-paper-plane"></i>
						<span>Offer</span>
					</a>
					<div id="collapsePersonnel" class="collapse" aria-labelledby="headingPersonnel"
						 data-parent="#accordionSidebar">
						<div class="bg-white py-2 collapse-inner rounded">
							<h6 class="collapse-header">Offer:</h6>
							<a class="collapse-item" asp-controller="Offer" asp-action="index">Offer List</a>
							<a class="collapse-item" asp-controller="Offer" asp-action="Create">Create Offer</a>

						</div>


					</div>
				</li>
			<!-- Divider -->
			<hr class="sidebar-divider">


			<!-- Sidebar Toggler (Sidebar) -->
			<div class="text-center d-none d-md-inline">
				<button class="rounded-circle border-0" id="sidebarToggle"></button>
			</div>


		</ul>
		<!-- End of Sidebar -->
		<!-- Content Wrapper -->
		<div id="content-wrapper" class="d-flex flex-column">

			<!-- Main Content -->
			<div id="content">

				<!-- Topbar -->
				<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

					<!-- Sidebar Toggle (Topbar) -->
					<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
						<i class="fa fa-bars"></i>
					</button>

					

					<!-- Topbar Navbar -->
					<ul class="navbar-nav ml-auto">

					</ul>

				</nav>
				<!-- End of Topbar -->
				<!-- Begin Page Content -->
				@RenderBody()

				<!-- /.container-fluid -->

			</div>
			<!-- End of Main Content -->
			<!-- Footer -->
			<!-- End of Footer -->

		</div>
		<!-- End of Content Wrapper -->

	</div>
	<!-- End of Page Wrapper -->
	<!-- Scroll to Top Button-->
	<a class="scroll-to-top rounded" href="#page-top">
		<i class="fas fa-angle-up"></i>
	</a>

	<!-- Logout Modal-->







	<!-- Bootstrap core JavaScript-->
	<script src="/startbootstrap/vendor/jquery/jquery.min.js"></script>
	<script src="/startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

	<!-- Core plugin JavaScript-->
	<script src="/startbootstrap/vendor/jquery-easing/jquery.easing.min.js"></script>

	<!-- Custom scripts for all pages-->
	<script src="/startbootstrap/js/sb-admin-2.min.js"></script>

	<!-- Page level plugins -->
	<script src="/startbootstrap/vendor/chart.js/Chart.min.js"></script>

	<!-- Page level custom scripts -->
	<script src="/startbootstrap/js/demo/chart-area-demo.js"></script>
	<script src="/startbootstrap/js/demo/chart-pie-demo.js"></script>
	<script src="~/startbootstrap/js/sb-admin-2.min.js"></script>
	<script src="~/startbootstrap/js/sb-admin-2.js"></script>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/jquery/dist/jquery.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)

</body>

</html>